export default [
  [
    'Bartek',
    'Kacper',
    'Stepan',
    'Klaudia',
    'Robert',
    'Marta',
    'Artsiom',
    'Vadzim',
    'Lina',
	'Ośmiornica',
	'Ciapek'
  ],
  [' przychodzi '],
  [
    'do Roberta',
    'do Marty',
    'do Kacpra',
    'do Klaudii',
    'do Vadzima',
    'do Liny',
    'do Galerii Dominikańskiej',
    'do Artsioma',
    'do mamy Stepana',
    'do Stepana',
    'do Bartka z Martą',
    'do polibudy',
    'do swojej zmywarki',
    'do Hanki',
    'do Haliny',
    'do Ciapka',
	'do ośmiornicy',
	'do więzienia',
	'do szpitala',
	'na cmentarz',
	'do zoo'
  ],
  [' i mówi: "'],
  [
    '(nic)',
    'jak tam, mordo?',
    'jak tam twoje ośmiornice?',
    'masz ochotę na spacerek?',
    'chodź, jebniemy piwka',
    'zagrajmy w civkę',
    'chcę kupę',
    'checesz kupę?',
    'chodźmy do kina',
    'jak żyjesz, tajny agencie?',
    'idziemy pić?',
	'raz na wozie, dwa podwozie',
	'do nogi',
	'kocham Cię',
	'kokokokoko',
	'nie, nie boję się',
	'dawaj fartucha',
	'tak naprawdę jestem rosyjskim szpiegiem',
	'sierżant Hopps jest sexy',
	'jesteś sexy',
	'otwórz cole',
	'jestem w ciąży'
  ],
  ['", a '],
  [
    'głos z nieba',
    'w odpowiedzi słyszy',
    'wszyscy na to',
	'wtem w oddali usłyszeli',
	'echo odpowiedziało',
	'na co on/ ona'
  ],
  [': "'],
  [
    'chcę kupę',
    'debilem jesteś?',
    'ja za',
    'znowu?',
    'nie!',
    'jeb się',
    'hoorray!!!',
    'idź w dupę',
    'zajebisty pomysł',
    'oczywiście, jak najbardziej',
    'muszę pilnować zmywarkę',
	'ty matole',
	'noooooooooo',
	'oj tak byczq, +1',
	'tak jak Pan Jezus powiedział',
	'hau hau'
  ],
  ['". '],
  [
    'Wszyscy milczeli.',
    'Cisza...',
    'Wszyscy poszli do kina.',
    'Marta poszła do domu.',
    'Wszyscy poszli na planszówki.',
    'A potem wszyscy ujebali sesję.',
	'I nie przeżył tego nikt.',
	'To było ostatni raz kiedy ich widziałem Panie władzo.',
	'Zmywarka znowu się zepsuła.',
	'Do Bartka przyjechali teściowie.',
	'Kacper się spóźnił.',
	'Ale toaleta była nieczynna.'
  ]
];
